#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Mar 09, 2025 06:30:23 PM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m80 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 750x553+673+100
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4420 1090
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Network Packet Generator"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    entry "$top.ent47" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 134 
    vTcl:DefineAlias "$top.ent47" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor sw \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -padx 5 \
        -relief ridge -text "status_bar" 
    vTcl:DefineAlias "$top.lab56" "status_bar" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Protcol" 
    vTcl:DefineAlias "$top.lab52" "Label3" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$top.lab47" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text " MAC addresses " -background #d9d9d9 -height 99 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 250 
    vTcl:DefineAlias "$top.lab47" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab47
    label "$site_3_0.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Source" 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Destination" 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent50" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent50" "src_mac_entry" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent51" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent51" "dst_mac_entry" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.24 -width 0 \
        -relwidth 0.35 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.56 -width 0 \
        -relwidth 0.35 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.417 -y 0 -rely 0.24 -width 124 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent51 \
        -in $site_3_0 -x 0 -relx 0.417 -y 0 -rely 0.56 -width 124 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab50" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -text " IPs " \
        -background #d9d9d9 -height 99 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -width 240 
    vTcl:DefineAlias "$top.lab50" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab50
    label "$site_3_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Source" 
    vTcl:DefineAlias "$site_3_0.lab51" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Destination" 
    vTcl:DefineAlias "$site_3_0.lab53" "Label5" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent54" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 114 
    vTcl:DefineAlias "$site_3_0.ent54" "src_ip_entry" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent55" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 114 
    vTcl:DefineAlias "$site_3_0.ent55" "dst_ip_entry" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.19 -width 0 \
        -relwidth 0.308 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.571 -width 0 \
        -relwidth 0.308 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 0 -relx 0.417 -y 0 -rely 0.19 -width 124 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 0 -relx 0.417 -y 0 -rely 0.571 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab57" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text " TCP settings " -background #d9d9d9 -height 103 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 249 
    vTcl:DefineAlias "$top.lab57" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab57
    label "$site_3_0.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "TTL" 
    vTcl:DefineAlias "$site_3_0.lab58" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab60" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Flag" 
    vTcl:DefineAlias "$site_3_0.lab60" "Label7" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent59" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent59" "ttl_entry" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent61" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent61" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.261 -width 0 \
        -relwidth 0.254 -height 0 -relheight 0.191 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.6 -width 0 \
        -relwidth 0.142 -height 0 -relheight 0.19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 0 -relx 0.417 -y 0 -rely 0.261 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 0 -relx 0.417 -y 0 -rely 0.6 -width 124 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab62" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -text " ICMP " \
        -background #d9d9d9 -height 102 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -width 240 
    vTcl:DefineAlias "$top.lab62" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab62
    label "$site_3_0.lab63" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Type" 
    vTcl:DefineAlias "$site_3_0.lab63" "Label8" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent64" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent64" "icmp_type_entry" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.3 -width 0 \
        -relwidth 0.308 -height 0 -relheight 0.21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 0 -relx 0.417 -y 0 -rely 0.3 -width 124 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    label "$top.lab65" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Destination Port" 
    vTcl:DefineAlias "$top.lab65" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab67" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "TOS" 
    vTcl:DefineAlias "$top.lab67" "Label10" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent68" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 94 
    vTcl:DefineAlias "$top.ent68" "tos_entry" vTcl:WidgetProc "Toplevel1" 1
    spinbox "$top.spi66" \
        -activebackground #d9d9d9 -background white \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -increment 1.0 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -to 65535.0 
    vTcl:DefineAlias "$top.spi66" "dst_port_entry" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent70" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 94 
    vTcl:DefineAlias "$top.ent70" "ip_id_entry" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab69" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "IP ID" 
    vTcl:DefineAlias "$top.lab69" "Label11" vTcl:WidgetProc "Toplevel1" 1
    menu "$top.m80" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    button "$top.but77" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "send_one" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Send one packat" 
    vTcl:DefineAlias "$top.but77" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but76" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "toggle_sending" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Start Sending" 
    vTcl:DefineAlias "$top.but76" "Button3" vTcl:WidgetProc "Toplevel1" 1
    checkbutton "$top.che71" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound right -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify right \
        -text "Encrypt Payload" -variable "che71" 
    vTcl:DefineAlias "$top.che71" "encrypt_checkbox" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but75" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Clean form" 
    vTcl:DefineAlias "$top.but75" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but74" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "load_defaults" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Load Default Values" 
    vTcl:DefineAlias "$top.but74" "Button1" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$top.lab78" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text " Output " -background #d9d9d9 -height 115 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 711 
    vTcl:DefineAlias "$top.lab78" "Labelframe5" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab78
    text "$site_3_0.tex79" \
        -background #d9d9d9 -font "-family {Segoe UI} -size 9" \
        -foreground black -height 64 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 -relief flat \
        -selectbackground #d9d9d9 -selectforeground black -state disabled \
        -width 684 -wrap word 
    $site_3_0.tex79 configure -font "TkTextFont"
    $site_3_0.tex79 insert end text
    vTcl:DefineAlias "$site_3_0.tex79" "Text1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tex79 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.962 -height 0 -relheight 0.674 -anchor nw \
        -bordermode ignore 
    text "$top.tex73" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 76 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 241 \
        -wrap word 
    $top.tex73 configure -font "TkTextFont"
    $top.tex73 insert end text
    vTcl:DefineAlias "$top.tex73" "payload_entry" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent47 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.044 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -y 0 -rely 0.956 -width 0 -relwidth 1.007 -height 0 \
        -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.044 -width 0 -relwidth 0.14 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.11 -width 0 -relwidth 0.333 \
        -height 0 -relheight 0.179 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.387 -y 0 -rely 0.11 -width 0 -relwidth 0.32 \
        -height 0 -relheight 0.179 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.307 -width 0 -relwidth 0.332 \
        -height 0 -relheight 0.186 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.387 -y 0 -rely 0.307 -width 0 -relwidth 0.32 \
        -height 0 -relheight 0.184 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.524 -width 0 -relwidth 0.184 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.597 -width 0 -relwidth 0.168 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.ent68 \
        -in $top -x 0 -relx 0.227 -y 0 -rely 0.597 -width 94 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.spi66 \
        -in $top -x 0 -relx 0.227 -y 0 -rely 0.524 -width 0 -relwidth 0.133 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.ent70 \
        -in $top -x 0 -relx 0.227 -y 0 -rely 0.669 -width 94 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.669 -width 0 -relwidth 0.124 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.but77 \
        -in $top -x 0 -relx 0.747 -y 0 -rely 0.108 -width 167 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but76 \
        -in $top -x 0 -relx 0.747 -y 0 -rely 0.181 -width 167 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che71 \
        -in $top -x 0 -relx 0.387 -y 0 -rely 0.506 -width 0 -relwidth 0.192 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.747 -y 0 -rely 0.651 -width 167 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 0 -relx 0.747 -y 0 -rely 0.579 -width 167 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab78 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.731 -width 0 -relwidth 0.948 \
        -height 0 -relheight 0.208 -anchor nw -bordermode ignore 
    place $top.tex73 \
        -in $top -x 0 -relx 0.387 -y 0 -rely 0.561 -width 0 -relwidth 0.321 \
        -height 0 -relheight 0.145 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

